### PR TITLE
Update 20170315

### PR DESCRIPTION
**Pull request by seansweda**
Not sure if this project is still actively maintained, but if so please consider for merging.

This is a series of commits that adds several features (all new functionality is disabled by default):
- option to suppress notifications if they are received on the currently active buffer
- option to suppress notifications based on matching nick/prefix
- support for /notify notifications
- support for /watch notifications

There is also a bugfix for ignore_old_messages.

### CODE REVIEW

**Comment by sindresorhus** [comment]
I don't use Weechat anymore, so I won't be able to test or maintain this code. Would you be interested in being added as a maintainer here?

The changes looks pretty good, but needs to be documented in the readme.

**Comment by seansweda** [comment]
Sure, did you still want to be involved for code review?

Agreed on the README, I'll get that updated.  I'll also take a crack at adding descriptions to the options to make them iset-friendly.

**Comment by sindresorhus** [comment]
Sure, I can review, no problem. I don't have time to set up WeeChat again and test the actual code.

**Comment by sindresorhus** [comment]
@seansweda Still interested?

**Comment by seansweda** [comment]
yes, doing this the right way is on my todo list, unfortunately most of my free time has been tied up in other projects

I'll try to get to it soon

**Comment by sindresorhus** [comment]
Closing this for now. @seansweda Let me know if you ever want to finish this and I'll reopen ;)

**Pull request closed without merging**
